version: '3.5'

networks:
  backend:
    driver: bridge

volumes:
  mysql:
    driver: local

services:
    mysql:
      build:
        context: mysql
        args:
          - MYSQL_VERSION=latest
      environment:
        - MYSQL_DATABASE=default
        - MYSQL_USER=default
        - MYSQL_PASSWORD=secret
        - MYSQL_ROOT_PASSWORD=root
        - TZ=UTC
      volumes:
        - ~/.data/mysql:/var/lib/mysql
        - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      ports:
        - "3306:3306"
      deploy:
        resources:
          limits:
            cpus: '0.5'
            memory: 500M
      networks:
        - backend
    myapp:
      build:
        context: .
      ports:
        - "8080:8080"
      deploy:
        resources:
          limits:
            cpus: '0.5'
            memory: 500M
      networks:
        - backend
